# Config File with ROS Parameters

# No. of Samples for the FMT* Planner
n_samples: 1000

# Max Radius between two nodes to be qualified as neighbours (in m)
near_radius: 0.5

# Rectangle for Uniform Sampling of Nodes with respect to origin of map(in m)
x_min: -15
x_max: 15
y_min: -10
y_max: 10

# Node Construction and Near Node Calculations
online: false